---
title: "03_Disc. Cartographie des discontinuités et lissages"
author: "R. Leconte"
date: "11/01/2022"
output: html_document
---
```{r pkg}

library(mapsf)
library(maptiles)
library(potential)

```

# 1. Cartographie des discontinuités
```{r disc}
# Auto-intersection des communes (avec buffer, en mètres)
com_borders  <- st_intersection(st_buffer(comsf_paris, 10), st_buffer(comsf_paris, 10)) 

# Transformation des géométries en 'MULTILINESTRING'
com_borders  <- st_cast(com_borders ,"MULTILINESTRING")

# Suppression des intersections entre un même polygone
com_borders  <- com_borders [com_borders$CODGEO != com_borders$CODGEO.1, ] 

# Construction d'un identifiant unique pour chaque frontière
com_borders$CODGEO1 <- com_borders$CODGEO
com_borders$CODGEO2 <- com_borders$CODGEO.1
com_borders$CODGEO <-  paste0(com_borders$CODGEO1, "_", com_borders$CODGEO2)
rownames(com_borders) <- com_borders$CODGEO
com_borders  <- com_borders [,c("CODGEO","CODGEO1","CODGEO2","geometry")]

plot(com_borders$geometry)


# Récupération de la variable d'intéret, en supprimant la géométrie associée
vals <- st_set_geometry(x = comsf_paris[, c("CODGEO","Q218")], 
                        value = NULL)

# Double jointure pour récupérer les valeurs des NUTS limitrophes
com_borders <- merge (x = com_borders, y = vals, by.x = "CODGEO1", by.y = "CODGEO", all.x = T)
com_borders <- merge (x = com_borders, y = vals, by.x = "CODGEO2", by.y = "CODGEO", all.x = T)


# calcul de la discontinuité relative
com_borders$disc <- com_borders$Q218.x / com_borders$Q218.y

# on ne conserve que les 5% des discontinuités les plus fortes
threshold <- 0.975
disc <- com_borders[com_borders$disc >= quantile(com_borders$disc,threshold),]


# cartographie
mf_map(comsf_paris, col = "grey80", border = "grey90")
mf_map(x = disc,
       var = "disc",
       col = "blue",
       lwd = 2,
       add = TRUE)

```


Raffiner la carte

```{r cartopretty}

# sélection des labels à ploter

bot <- comsf_paris %>% 
top_n(wt = Q218, -5)

top <- comsf_paris %>% 
  top_n(wt = Q218, 5)

topbot <- bind_rows(top, bot)


# carte

mf_map(comsf_paris, 
       var = "Q218", 
       type = "choro", 
       breaks = "q6",
       pal =  hcl.colors(6, "teal", rev = TRUE), 
       border = NA, 
       leg_title = "Revenu médian\n(discrétisation Q6)")
mf_map(x = disc,
       col = "red",
       lwd = 3,
       add = TRUE)
mf_label( topbot, 
          var = "nom",
          cex = 0.5,
          col = "black",
          overlap = FALSE,
          lines = TRUE,
          halo=FALSE)
mf_layout(title = "Les discontinuités sociales les plus fortes dans l'unité urbaine de Paris (2018)",
    credits = "Auteur: R. Leconte, 2022. Données: INSEE, Filosofi, 2018",
    arrow = FALSE)
 mf_theme("default")

```
Option cartographique avec tuile

```{r}

# charger des tuiles
paris_osm <- get_tiles(comsf_paris, provider = "OpenStreetMap", crop = TRUE)
paris_img <- get_tiles(comsf_paris, provider = "Esri.WorldImagery", crop = TRUE)
paris_db <- get_tiles(comsf_paris, provider = "CartoDB.PositronNoLabels", crop = TRUE)

# voir la tuile
plot_tiles(paris_db)


# créer le contour de notre aire d'étude

contour <- st_union(comsf_paris)

# l'ajouter en fond de carte

mf_raster(paris_osm)
mf_map(x = disc,
       col = "red",
       lwd = 3,
       add = TRUE)
mf_map(contour, col = NA, add = TRUE)



```


# 2. Cartes lissées


```{r pot}


# création d'une grille de points régulière pour lesquels seront calculées les valeurs de la variable
y <- create_grid(x = comsf_paris, res = 5000)

# création d'une matrice de distance entre les points d'origine (centroides des communes), et les points de la grille
d <- create_matrix(x = comsf_paris, y = y)

# calcul du potentiel
# fun = exponentielle
# span = distance à laquelle la valeur vaut 50% de celle du point d'origine
# beta = exposant de la distance 

y$pot <- potential(x = comsf_paris, y = y, d = d,
                   var = "Q218", fun = "e",
                   span = 3000, beta = 2)

# calcul de l'équipotentiel : transformation des points en zones
iso <- equipotential(x = y, var = "pot", breaks = seq(min(y$pot),max(y$pot), 500), mask = comsf_paris)


mf_map(x = iso, var = "center", type = "choro", 
       breaks = "equal", 
       nbreaks = 6,
       pal = hcl.colors(6, "teal", rev = TRUE),
       lwd = .2,
       border = NA, 
       leg_pos = "topleft",
       leg_val_rnd = 0,
       leg_title = "Potentiel de revenu\n(portée = 3km, exposant = 2) ")
mf_map(contour, col = NA, add=TRUE)
mf_label( topbot, 
          var = "nom",
          cex = 0.5,
          col = "black",
          overlap = FALSE,
          lines = FALSE,
          halo=FALSE)
mf_layout(title = "Le potentiel de revenu dans l'unité urbaine de Paris (2018)",
    credits = "Auteur: R. Leconte, 2022. Données: INSEE, Filosofi, 2018",
    arrow = FALSE)

```


