---
title: "03_Flow. Cartographie statistique 2 : flux"
author: "R. Leconte"
date: "2026-01-14"
output: html_document
---


```{r pkg}
library(sf)
library(mapsf)
library(dplyr)


setwd("D:/ENS_ULM/cours/SPACER/2026/")

```



# 1. Préparation des données
## 1.1. Chargement

```{r data}
# Table des données

# Importantion de la table filtrée sur la région d'intérêt

migcom_idf <- read.csv("migcom_idf.csv")


```


## 1.2. Préparation de la table de flux


```{r data_flow}
# Table des flux internes à la région

flow <- migcom_idf %>% 
  filter(DEP %in% dep_idf & DEPAN %in% dep_idf) %>% 
  select(CODGEO, DCRAN, IPONDI) %>% 
  group_by(CODGEO,DCRAN) %>% 
  summarise(FIJ = sum(IPONDI)) %>% 
  filter(CODGEO != DCRAN) %>% 
  rename(ORIG = DCRAN, DEST = CODGEO)

```
## 1.3 Préparation de la géométrie


```{r data_geo}
# Communes de la région

# charger la géométrie avec sf
comsf <- st_read(dsn = "com_aav2020_2024/com_aav2020_2024.shp", 
                  stringsAsFactors = F)


########
# récupérer les arrondissements municipaux 
#https://geoservices.ign.fr/adminexpress 

arrt <- st_read("arrondissement_municipal/ARRONDISSEMENT_MUNICIPAL.shp")


arrt <- left_join(arrt, st_drop_geometry(comsf),  by = c("INSEE_COM" = "codgeo"))


arrt <- arrt %>% 
  select (NOM, INSEE_ARM, aav2020, libaav2020, cateaav, dep, reg, geometry)%>% 
  rename(libgeo = NOM, codgeo =  INSEE_ARM) 


comsf_arrt <- rbind(comsf, arrt)

comsf_arrt <- comsf_arrt %>%
  filter(!codgeo %in% c("75056","69123","13055"))

#######


# filtrer comme un data frame
comsf_idf <- comsf_arrt %>% 
  filter(dep %in% dep_idf) %>% 
  rename(CODGEO = codgeo)

plot(comsf_idf$geometry)

# interroger le système de coordoonées 
st_crs(comsf_idf)

# projeter le fond de carte dans le référentiel Lambert93 (adapté pour la France)
comsf_idf <- st_transform(comsf_idf, crs = 2154)

# visualiser la géométrie
plot(comsf_idf$geometry)



```


# 2. Cartographie avec MAPSF

## 2.1 Créer la géométrie des liens

```{r links}
links <-
  mf_get_links(
    x = comsf_idf,
    df = flow,
    x_id = "CODGEO",
    df_id = c("ORIG", "DEST")  )


```

## 2.2 Cartographier les liens : l'effet spaghetti

```{r carto1}

mf_map(comsf_idf,
       col = "grey",
       border = "#3b3b3b",
       add = TRUE)
mf_map(links, col = "yellow", add = TRUE)

```
## 2.2 Filtrer la matrice

```{r}
# Filtrage absolu : les principaux flux 

links_big <- links %>% 
  filter(FIJ>200)

mf_map(comsf_idf,
       col = "grey",
       border = "#3b3b3b",
       add = TRUE)
mf_map(links_big, col = "yellow", add = TRUE)


#Filtrage relatif : le flux sortant le plus important de chaque commune

links_max <- links %>%
  filter(FIJ>10) %>% 
  group_by(ORIG) %>%
  slice_max(FIJ, n = 1, with_ties = FALSE) %>%
  ungroup()


mf_map(comsf_idf,
       col = "grey",
       border = "#3b3b3b",
       add = TRUE)
mf_map(links_max, col = "yellow", add = TRUE)

```
## 2.3 Adapter l'échelle et filtrer davantage

```{r dept}

# regrouper les communes en département 
depsf_idf <- comsf_idf %>% 
  group_by(dep) %>%
  summarise(geometry = st_union(geometry), .groups = "drop")


# agréger les flux par département

flow_dep <- migcom_idf %>% 
  filter(DEP %in% dep_idf & DEPAN %in% dep_idf) %>% 
  select(DEP, DEPAN, IPONDI) %>% 
  group_by(DEP,DEPAN) %>% 
  summarise(FIJ = sum(IPONDI)) %>% 
  filter(DEP != DEPAN) %>% 
  rename(ORIG = DEPAN, DEST = DEP)

# sélectionner les flux au départ de Paris

flow_paris <- flow_dep %>% 
  filter(ORIG == "75")


links_paris <-
  mf_get_links(
    x = depsf_idf,
    df = flow_paris,
    x_id = "dep",
    df_id = c("ORIG", "DEST")  )


mf_map(depsf_idf,
       col = "grey",
       border = "#3b3b3b",
       add = TRUE)
mf_map(
  links_paris,
  var = "FIJ",
  col = 
    "yellow",
  border = "white",
  type = "prop",
  inches = 10,
  leg_title_cex = 0.8,
  leg_val_cex   = 0.6,
  leg_pos = "topright",
  leg_title = "Nombre de déménagements \nau départ de Paris"
)
mf_label(depsf_idf, 
         var = "dep")
mf_layout(title = "Quitter Paris", 
    credits = "Auteur: R. Leconte, 2026. Données: INSEE, RP 2022",
    arrow = FALSE)



```

